# ============================= Network Variables =============================
ipvar HOME_NET 192.168.56.0/24
ipvar EXTERNAL_NET any

# ============================= Rule Paths =============================
var RULE_PATH /etc/snort/rules
include $RULE_PATH/local.rules

# ============================= Output Plugins =============================
output alert_fast: /var/log/snort/alert

# ============================= Logging =============================
logdir /var/log/snort

# ============================= Network Decoder =============================
config checksum_mode: all

# ============================= Detection Engine =============================
config detection: search-method ac-split

# ============================= Performance =============================
config profile_rules: print 10

# ============================= Include Classification =============================
include classification.config
include reference.config
